### PR TITLE
Tech ydiago

### PR DESCRIPTION
**Pull request by sangallidavide**
* elpa library can now be passed to yambo configure (internal fallback not yet working)
These are my options
```--with-elpa-libs="/usr/lib/x86_64-linux-gnu/libelpa.a" --with-elpa-includedir="/usr/include/elpa/" \```
ydiago library automatically gets the info

* ydiag_solver can be controlled from yambo input
```BSSydiaLib = "e"   # [BSS] Library used with ydiago solver '(s)calapack/(e)lpa' ```

### CODE REVIEW

**Comment by sangallidavide** [comment]
For info. I tested ELPA vs Scalapack on our local cluster in Rome.

Matrix size 10^4, 25 MPI tasks.
In the resonant case I do not see any difference
```
SLK   Ydiago Solver :     46.5162s CPU
ELPA  Ydiago Solver :     45.1268s CPU
```

In the coupling case instead there is a decent speed-up
```
SLK   Ydiago Solver :    324.0711s CPU
ELPA  Ydiago Solver :    275.9568s CPU
```

I had to compile elpa with the following options
```--disable-sse-kernels --disable-avx-kernels --disable-avx2-kernels --disable-avx512-kernels```
and I get some warning messages.
```
warning You did not request SSE support but your local CPU supports it
warning You did not request AVX2 support but your local CPU supports it
```
Not sure on how much impact this has on the simulation time, but I'm not able to compile without the `--disable-*` options

**Comment by muralidhar-nalabothula** [comment]
```--disable-sse-kernels --disable-avx-kernels --disable-avx2-kernels --disable-avx512-kernels``` implies you did not turn on any optimisations. Not surprised with the results. since your cpu supports avx2, you can try the following ```./configure FC=mpif90 CC=mpicc FCFLAGS="-O2 -ffree-line-length-none -march=native" CFLAGS="-O2 -march=native" CPP="cpp -E" LDFLAGS=" -lscalapack  -lopenblas" --disable-avx512 --enable-c-tests=no --enable-cpp-tests=no --enable-fortran-tests=no --prefix=xxx```

**Comment by sangallidavide** [comment]
Ok, passing  `-march=native` to `CFLAGS` fixed the compilation with SSE and AVX2

**Comment by sangallidavide** [comment]
Ok, after fixing everything the speed-up is there

Matrix size 10^4, 25 MPI tasks.
```
SLK   Ydiago Solver :     46.5162s CPU
ELPA  Ydiago Solver :     25.8624s CPU
```

```
SLK   Ydiago Solver :    324.0711s CPU
ELPA  Ydiago Solver :    115.1378s CPU
```

**Pull request merged**
